const lvls = [
  [
    {id: 1, value: 'A'},
    {id: 2, value: 'A'},
    {id: 3, value: 'B'},
    {id: 4, value: 'B'},
    {id: 5, value: 'C'},
    {id: 6, value: 'C'},
    {id: 7, value: 'D'},
    {id: 8, value: 'D'},
  ],[
    {id: 1, value: 'A'},
    {id: 2, value: 'A'},
    {id: 3, value: 'B'},
    {id: 4, value: 'B'},
    {id: 5, value: 'C'},
    {id: 6, value: 'C'},
    {id: 7, value: 'D'},
    {id: 8, value: 'D'},
    {id: 9, value: 'E'},
    {id: 10, value: 'E'},
    {id: 11, value: 'F'},
    {id: 12, value: 'F'},
    {id: 13, value: 'G'},
    {id: 14, value: 'G'},
    {id: 15, value: 'H'},
    {id: 16, value: 'H'},
  ],[
    {id: 1, value: 'A'},
    {id: 2, value: 'A'},
    {id: 3, value: 'B'},
    {id: 4, value: 'B'},
    {id: 5, value: 'C'},
    {id: 6, value: 'C'},
    {id: 7, value: 'D'},
    {id: 8, value: 'D'},
    {id: 9, value: 'E'},
    {id: 10, value: 'E'},
    {id: 11, value: 'F'},
    {id: 12, value: 'F'},
    {id: 13, value: 'G'},
    {id: 14, value: 'G'},
    {id: 15, value: 'H'},
    {id: 16, value: 'H'},
    {id: 17, value: 'I'},
    {id: 18, value: 'I'},
    {id: 19, value: 'J'},
    {id: 20, value: 'J'},
    {id: 21, value: 'K'},
    {id: 22, value: 'K'},
    {id: 23, value: 'L'},
    {id: 24, value: 'L'},
  ]
];
